### ISSUE TITLE
 http://nlpviz.bpodgursky.com/home is down

### ISSUE THREAD

**Issue by duncanawoods** [bpodgursky/nlpviz#10]
This site is linked from d3 showcase and is given as the source location for this project too so it would be great if it worked. Thanks!

**Comment by bpodgursky** [comment]
Unfortunately I didn't plan well and I'm not going to be able to get to that site to fix it for a couple weeks (took a trip and left the laptop with the ssh key behind), but I'll get that up as soon as I'm able.

**Comment by duncanawoods** [comment]
Fantastic thanks. FYI I think its popular because its the best looking vertical tree example in the d3 showcase.

**Comment by bpodgursky** [comment]
Back up, and I think I understand now why it went down.  Thanks!

**Comment by duncanawoods** [comment]
thanks!
