### ISSUE TITLE
What machine specs are you deployed on?

### ISSUE THREAD

**Issue by scottyli** [bpodgursky/nlpviz#5]
I noticed your hosted example (http://nlpviz.bpodgursky.com/home) has an incredible API response time.

Your hosted site:                              ~100ms (including network latency!)
My local machine (macbook 2013): ~200ms (without network latency)

What are you hosting on?

**Comment by bpodgursky** [comment]
It's actually on a really low spec digitalocean box.  I'm away from my
computer for a few days and don't remember exactly but it's the 1 or 2 g
droplet.  But it's behind an nginx cache, so make sure you're running
unique queries each time to get a fair comparison.

**Comment by scottyli** [comment]
Ah the cache, that would've been it. Thanks!
